els-ASAP auto commit file/tag openscap-1.2.13-2.el6.src.rpm

diff --git a/src/utils/oscap-vm b/src/utils/oscap-vm
--- a/src/utils/oscap-vm
+++ b/src/utils/oscap-vm
@@ -22,10 +22,6 @@ function die()
     exit 1
 }
 
-which guestmount > /dev/null || die "Cannot find guestmount, please install libguestfs utilities."
-which guestunmount > /dev/null || die "Cannot find guestunmount, please install libguestfs utilities."
-which mktemp > /dev/null || die "Cannot find mktemp, please install coreutils."
-
 function usage()
 {
     echo "oscap-vm -- Tool for offline SCAP evaluation of virtual machines."
@@ -96,6 +92,19 @@ else
     die
 fi
 
+hash guestmount 2> /dev/null || die "Cannot find guestmount, please install libguestfs utilities."
+
+if hash guestunmount 2> /dev/null; then
+    UNMOUNT_COMMAND="guestunmount"
+elif hash fusermount 2> /dev/null; then
+    echo "guestunmount command not present on the system, using simpler fusermount instead"
+    UNMOUNT_COMMAND="fusermount -u"
+else
+    die "Cannot find guestunmount or fusermount, please install libguestfs utilities, or fuse."
+fi
+
+hash mktemp 2> /dev/null || die "Cannot find mktemp, please install coreutils."
+
 MOUNTPOINT=$(mktemp -d)
 
 if [ "$1" == "image" ]; then
@@ -120,6 +129,6 @@ shift 2
 oscap "$@"
 EXIT_CODE=$?
 echo "Unmounting '$MOUNTPOINT'..."
-guestunmount "$MOUNTPOINT"
+$UNMOUNT_COMMAND "$MOUNTPOINT"
 rmdir "$MOUNTPOINT"
 exit $EXIT_CODE
